dist: bionic

env:
  - WRADLIB_VER=1.7.1 DOCKER_REPO=wradlib-docker

jobs:
  include:
    - stage: build base image
      script:
        - cd base
        - export fetch_status=`docker pull wradlib/${DOCKER_REPO}:base > /dev/null && echo 1 || echo 0`
        - if [  "${fetch_status}" == "0" ]; then
            docker build -t wradlib/$DOCKER_REPO:base .;
            docker images;
            echo "$DOCKER_PW" | docker login -u $DOCKER_ID --password-stdin;
            docker push wradlib/$DOCKER_REPO:base;
          fi;
    - stage: build min image
      script:
        - docker build --build-arg WRADLIB_VER --build-arg WRADLIB_DOCKER_TAG=min --build-arg DOCKER_REPO -t wradlib/$DOCKER_REPO:$WRADLIB_VER-min .
        - docker images
        - echo "$DOCKER_PW" | docker login -u $DOCKER_ID --password-stdin
        - docker push wradlib/$DOCKER_REPO:$WRADLIB_VER-min
    - stage: build full image
      script:
        - docker build --build-arg WRADLIB_VER --build-arg WRADLIB_DOCKER_TAG=full --build-arg DOCKER_REPO -t wradlib/$DOCKER_REPO:$WRADLIB_VER-full .
        - docker images
        - echo "$DOCKER_PW" | docker login -u $DOCKER_ID --password-stdin
        - docker push wradlib/$DOCKER_REPO:$WRADLIB_VER-full
