dist: bionic

env:
  - WRADLIB_VER=${TRAVIS_TAG} DOCKER_REPO=wradlib-docker

jobs:
  include:
    - stage: build base image
      script:
        - cd base
        - export fetch_status=`docker pull wradlib/${DOCKER_REPO}:base > /dev/null && echo 1 || echo 0`
        - if [  "${fetch_status}" == "0" ]; then
            docker build -t wradlib/$DOCKER_REPO:base .;
            docker images;
            echo "$DOCKER_PW" | docker login -u $DOCKER_ID --password-stdin;
            docker push wradlib/$DOCKER_REPO:base;
          fi;
    - stage: build min image
      script:
        - if [ "${WRADLIB_VER}" == "" ]; then
            export WRADLIB_VER=master;
          fi;
        - export WRADLIB_DOCKER_TAG=min
        - docker build --build-arg WRADLIB_VER --build-arg WRADLIB_DOCKER_TAG --build-arg DOCKER_REPO -t wradlib/$DOCKER_REPO:$WRADLIB_VER-${WRADLIB_DOCKER_TAG} .
        - docker images
        - echo "$DOCKER_PW" | docker login -u $DOCKER_ID --password-stdin
        - docker push wradlib/$DOCKER_REPO:$WRADLIB_VER-${WRADLIB_DOCKER_TAG}
    - stage: build full image
      script:
        - if [ "${WRADLIB_VER}" == "" ]; then
            export WRADLIB_VER=master;
          fi;
        - export WRADLIB_DOCKER_TAG=full
        - docker build --build-arg WRADLIB_VER --build-arg WRADLIB_DOCKER_TAG --build-arg DOCKER_REPO -t wradlib/$DOCKER_REPO:$WRADLIB_VER-${WRADLIB_DOCKER_TAG} .
        - docker images
        - echo "$DOCKER_PW" | docker login -u $DOCKER_ID --password-stdin
        - docker push wradlib/$DOCKER_REPO:$WRADLIB_VER-${WRADLIB_DOCKER_TAG}
