name: wradlib
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.8
  - ipykernel
  - cartopy
  - deprecation
  - gdal
  - git
  - h5py
  - h5netcdf
  - matplotlib
  - netCDF4
  - numpy
  - requests
  - scipy
  - semver
  - xarray
  - xmltodict
